apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karpenter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "karpenter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "karpenter.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "karpenter.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.operator.metricsPort }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.operator.healthProbePort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "karpenter.secretName" . }}
          env:
            - name: SPOT_CLOUDSPACE_NAME
              value: {{ required "spot.cloudspaceName is required" .Values.spot.cloudspaceName | quote }}
            {{- if .Values.spot.baseURL }}
            - name: SPOT_BASE_URL
              value: {{ .Values.spot.baseURL | quote }}
            {{- end }}
            {{- if .Values.spot.oauthURL }}
            - name: SPOT_AUTH_URL
              value: {{ .Values.spot.oauthURL | quote }}
            {{- end }}
            {{- if .Values.operator.disableLeaderElection }}
            - name: DISABLE_LEADER_ELECTION
              value: "true"
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
