{{- if and .Values.spot.refreshToken (not .Values.spot.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPOT_REFRESH_TOKEN: {{ .Values.spot.refreshToken | quote }}
{{- end -}}
